### ISSUE TITLE
Hi I tried to install the package through PIP and I am using the latest pip 21.3.1 and encountering the error

### ISSUE THREAD

**Issue by Kaustav-93** [timyerg/venny4py#2]
ERROR: Could not find a version that satisfies the requirement venny4py (from versions: none)
ERROR: No matching distribution found for venny4py

**Comment by timyerg** [comment]
Hi!
Did you run:
`pip install venny4py`
? Without spelling mistakes? 

Could you also try specify the version?
`pip install venny4py==1.0.1`

Just tested it in environments with python 3.8 and 3.12 and it works.
I use pip 23.3.1

Which python version do you have? If lower than 3.7, then try to install into another environment with python >=3.7, or upgrade python or create new conda environment with python >=3.7

**Comment by timyerg** [comment]
Closed with no response.
